export const GET_DATA = 'GET_DATA';
export const ADD_DATA = 'ADD_DATA';

export const SET_SELECTED_COMPANY_ID_AND_NAME = 'SET_SELECTED_COMPANY_ID_AND_NAME';

export const TOGGLE_LIKED_STATION = 'TOGGLE_LIKED_STATION';
export const UPDATE_ARRAY_WITH_LIKED_STATIONS = 'UPDATE_ARRAY_WITH_LIKED_STATIONS';

export const CHANGE_LOADER_STATUS = 'CHANGE_LOADER_STATUS';
export const SET_ERROR_TEXT = 'SET_ERROR_TEXT';
